"""Added user_id to posts

Revision ID: 073be51dcf73
Revises: 99c4db85db55
Create Date: 2024-10-21 21:34:36.873567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073be51dcf73'
down_revision = '99c4db85db55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_posts_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
